### ISSUE TITLE
Volume Bar?

### ISSUE THREAD

**Issue by Aersaud** [heyarne/airsonic-ui#40]
I was testing it out and so far I must say its amazing. One thing I noticed missing is a volume bar.

**Comment by heyarne** [comment]
Thanks for the feedback! It's true that there is no volume bar because I never quite understood the benefit of having one. In general my tracks all have the same gain more or less; when I want to mute the player I either pause or use the "mute tab" functionality in Firefox (which exists in Chrome as well I think). Can you tell me how you use the volume controls in the player itself?

**Comment by heyarne** [comment]
Hey, I implemented something, didn't have time to test it much. You can find it either in the pull request above or deployed at https://heyarne.github.io/airsonic-ui.

Let me know if it works!

**Comment by heyarne** [comment]
Branch is merged, closing this for now
