### ISSUE TITLE
Increase information density on the landing page

### ISSUE THREAD

**Issue by jvoisin** [heyarne/airsonic-ui#50]
When logged in, on the landing page, I can only see 5 albums, while on the old interface it's almost two times more.

![aaa](https://user-images.githubusercontent.com/325724/55938427-e4e36380-5c2a-11e9-9960-f76e1fbab6de.png)

**Comment by almet** [comment]
In bulma, the minimum supported size [seems to be one-fifth](https://bulma.io/documentation/columns/sizes/).

One other way would be to reduce the place the titles and headcrumb is taking.

**Comment by heyarne** [comment]
This isn't really restricted to Bulma, because of course you could just write smaller columns yourself. Once you do smaller columns the album title won't be readable. In my case it often already gets cut off or abbreviated with "…".

I persoally never noticed this as a problem because I'm only interested in the first couple of items there anyways. I know that's a non-argument, because obviously there *are* more elements and you can even paginate. :)

If the space above is restricted (which I think would be ok), it should be done consistently. There's also not a whole lot to reduce because all of these elements need a bit of vertical space to not look too cramped I think.
